### ISSUE TITLE
image in h3 tag

### ISSUE THREAD

**Issue by rittermo** [liqd/liquidsite#26]
Images in the 2-column element is sometime wrapped in a h3 tag, which causes different heights and margins for text-image combinations: https://liqd.net/de/products/
![bildschirmfoto 2016-10-17 um 15 26 42](https://cloud.githubusercontent.com/assets/15341015/19439377/23113ef6-947e-11e6-9e1b-a5f26e37dc7a.png)

**Comment by vellip** [comment]
That happened because the image was literally inside an <h3 />, must've happened while editing
