### ISSUE TITLE
left aligned images

### ISSUE THREAD

**Issue by rittermo** [liqd/liquidsite#29]
The new left aligned text is great for the eyes! The only instance where it creates problems is that some icons/images that were centered before are now left aligned. 

Three Images Element – About Page (https://liqd.net/de/about/)
Images posted in text editor as full-width (for example on http://liqd.net/products)

**Comment by rittermo** [comment]
Ah, an I just saw, that some buttons have left-aligned labels now, for example “Adhocracy vs. Facebook“ in a gray paragraph on https://liqd.net/de/products/

**Comment by MagdaN** [comment]
On Blogentries the subtitles and creator should also be centred: 
![bildschirmfoto 2016-10-24 um 14 06 45](https://cloud.githubusercontent.com/assets/2905743/19645096/57a4651a-99f3-11e6-8b95-b6aca0bd6833.png)
