### ISSUE TITLE
wagtail modeltranslations not in requirements

### ISSUE THREAD

**Issue by MagdaN** [liqd/liquidsite#3]
but its not needed anymore, isn't is? Its still imported somewhere

**Comment by meisterkaiser** [comment]
the only reference to modeltranslation is in the migrations :)

Since migrations do not work as expected (#4) anyway - and there's no critical data to migrate yet:
could you delete all core migrations including "0009_auto ...." and up and check if that solves the problem?

**Comment by MagdaN** [comment]
Yes, I will try this
